--Query for Questions 1-6
SELECT Customer_id, zip, Area, County, Age, Education, Employment, Job, Marital, Gender, HighBlood, Stroke, Complication_Risk, Overweight, Arthritis, Diabetes, Hyperlipidemia, BackPain, Anxiety, Allergic_rhinitis, Reflux_esophagitis, Asthma
INTO dbo.CUSTOMER_KEY_INFORMATION
FROM dbo.INPUT_DATA

SELECT DISTINCT zip, Population, City, State
INTO dbo.LOCATION
FROM dbo.INPUT_DATA

GO
ALTER TABLE dbo.LOCATION ADD CONSTRAINT LOCATION_PK PRIMARY KEY(zip)

SELECT DISTINCT Age, SeniorCitizen
INTO dbo.SENIOR_CITIZEN_STATUS
FROM dbo.INPUT_DATA

GO
ALTER TABLE dbo.SENIOR_CITIZEN_STATUS ADD CONSTRAINT SENIOR_CITIZENS_STATUS_PK PRIMARY KEY(Age)

GO
ALTER TABLE dbo.CUSTOMER_KEY_INFORMATION ADD CONSTRAINT CUSTOMER_KEY_INFORMATION_PK PRIMARY KEY(Customer_id)
ALTER TABLE dbo.CUSTOMER_KEY_INFORMATION ADD FOREIGN KEY (zip) REFERENCES LOCATION(zip)
ALTER TABLE dbo.CUSTOMER_KEY_INFORMATION ADD FOREIGN KEY (Age) REFERENCES SENIOR_CITIZEN_STATUS (Age)