--Query for Question 9
SELECT COUNT(Asthma) Asthma_count
FROM dbo.CUSTOMER_KEY_INFORMATION JOIN dbo.SENIOR_CITIZEN_STATUS ON CUSTOMER_KEY_INFORMATION.Age = SENIOR_CITIZEN_STATUS.Age
WHERE SeniorCitizen = 'Yes' AND Asthma = 'Yes'

SELECT COUNT(Overweight) Overweight_count
FROM dbo.CUSTOMER_KEY_INFORMATION JOIN dbo.SENIOR_CITIZEN_STATUS ON CUSTOMER_KEY_INFORMATION.Age = SENIOR_CITIZEN_STATUS.Age
WHERE SeniorCitizen = 'Yes' AND Overweight = 'Yes'

SELECT COUNT(HighBlood) HighBlood_count
FROM dbo.CUSTOMER_KEY_INFORMATION JOIN dbo.SENIOR_CITIZEN_STATUS ON CUSTOMER_KEY_INFORMATION.Age = SENIOR_CITIZEN_STATUS.Age
WHERE SeniorCitizen = 'Yes' AND HighBlood = 'Yes'

SELECT COUNT(Anxiety) Anxiety_count
FROM dbo.CUSTOMER_KEY_INFORMATION JOIN dbo.SENIOR_CITIZEN_STATUS ON CUSTOMER_KEY_INFORMATION.Age = SENIOR_CITIZEN_STATUS.Age
WHERE SeniorCitizen = 'Yes' AND Anxiety = 'Yes'

SELECT COUNT(Hyperlipidemia) Hyperlipidemia_count
FROM dbo.CUSTOMER_KEY_INFORMATION JOIN dbo.SENIOR_CITIZEN_STATUS ON CUSTOMER_KEY_INFORMATION.Age = SENIOR_CITIZEN_STATUS.Age
WHERE SeniorCitizen = 'Yes' AND Hyperlipidemia = 'Yes'

SELECT COUNT(Reflux_esophagitis) Reflux_esophagitis_count
FROM dbo.CUSTOMER_KEY_INFORMATION JOIN dbo.SENIOR_CITIZEN_STATUS ON CUSTOMER_KEY_INFORMATION.Age = SENIOR_CITIZEN_STATUS.Age
WHERE SeniorCitizen = 'Yes' AND Reflux_esophagitis = 'Yes'

SELECT COUNT(Allergic_rhinitis) Allergic_rhinitis_count
FROM dbo.CUSTOMER_KEY_INFORMATION JOIN dbo.SENIOR_CITIZEN_STATUS ON CUSTOMER_KEY_INFORMATION.Age = SENIOR_CITIZEN_STATUS.Age
WHERE SeniorCitizen = 'Yes' AND Allergic_rhinitis = 'Yes'

SELECT COUNT(BackPain) BackPain_count
FROM dbo.CUSTOMER_KEY_INFORMATION JOIN dbo.SENIOR_CITIZEN_STATUS ON CUSTOMER_KEY_INFORMATION.Age = SENIOR_CITIZEN_STATUS.Age
WHERE SeniorCitizen = 'Yes' AND BackPain = 'Yes'

SELECT COUNT(Arthritis) Arthritis_count
FROM dbo.CUSTOMER_KEY_INFORMATION JOIN dbo.SENIOR_CITIZEN_STATUS ON CUSTOMER_KEY_INFORMATION.Age = SENIOR_CITIZEN_STATUS.Age
WHERE SeniorCitizen = 'Yes' AND Arthritis = 'Yes'

SELECT COUNT(Stroke) Stroke_count
FROM dbo.CUSTOMER_KEY_INFORMATION JOIN dbo.SENIOR_CITIZEN_STATUS ON CUSTOMER_KEY_INFORMATION.Age = SENIOR_CITIZEN_STATUS.Age
WHERE SeniorCitizen = 'Yes' AND Stroke = 'Yes'

SELECT COUNT(Diabetes) Diabetes_count
FROM dbo.CUSTOMER_KEY_INFORMATION JOIN dbo.SENIOR_CITIZEN_STATUS ON CUSTOMER_KEY_INFORMATION.Age = SENIOR_CITIZEN_STATUS.Age
WHERE SeniorCitizen = 'Yes' AND Diabetes = 'Yes'

USE MEDICAL_INFO;
GO
SELECT CUSTOMER_KEY_INFORMATION.Customer_id, SENIOR_CITIZEN_STATUS.Age, CUSTOMER_KEY_INFORMATION.Overweight
FROM dbo.CUSTOMER_KEY_INFORMATION JOIN dbo.SENIOR_CITIZEN_STATUS ON CUSTOMER_KEY_INFORMATION.Age = SENIOR_CITIZEN_STATUS.Age
WHERE SeniorCitizen = 'Yes' AND Overweight = 'Yes'
ORDER BY Age ASC;